apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-env
  namespace: "{{ .Release.Namespace }}"
data:
  PUID: "{{ .Values.configmap_env.data.PUID }}"
  PGID: "{{ .Values.configmap_env.data.PGID }}"
  TZ:   "{{ .Values.configmap_env.data.TZ }}"
