apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-web"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  ports:
    - port: 8181
      protocol: TCP
      name: webui
  selector:
    app: "{{ .Release.Name }}"
  type: NodePort
