apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  storageClassName: "{{ .Values.pvc.storageclass }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pvc.size }}"
